version: 2
updates:
  - package-ecosystem: "nuget"
    directory: ".dependabot/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "tests/.dependabot/"
    schedule:
      interval: "daily"