version: 2
updates:
  - package-ecosystem: "nuget"
    directory: ".dependabot/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "ghul.compiler"
